local profiles = {{name="Oscar Ryley",linkedin="linkedin.com/in/oscar-ryley/",posts=3,average=0.3333,classification="human",posts_data={{text="Wrapping up an inspiring summer at the NQCC!\n\nOur 2025 summer placement students recently wrapped...",probability=1,class="ai",report="This LinkedIn post exhibits several hallmarks often associated with generic AI writing, primarily in its **stylistic choices and phrasing**:\n\n1.  **Over-reliance on generic positive adjectives:** Words like \"inspiring,\" \"incredible,\" \"outstanding,\" \"truly remarkable,\" \"huge thank you,\" \"big well done,\" and \"very best\" are used frequently to convey enthusi..."},{text="💡Quantum Computing for Energy Workshop💡\n\nI facilitated for the NQCC's workshop, bridging the gap...",probability=5.2789136414900325e-06,class="human",report="This LinkedIn post shows **no concrete signs of generic AI writing, unsupported factual claims, or manipulation.**\n\n**Explanation:**\nThe post contains specific, personal details and observations that are characteristic of human authorship, such as \"seeing my branding on screens and banners,\" \"attendees commenting on the contrast of discussing the future o..."},{text="🎮 DurJam: Remastered (2025) 🎮\n\nSparked by the positive reception to my Godot Tutorial for DurHack...",probability=8.265566845533782e-06,class="human",report="The LinkedIn post exhibits strong indicators of human authorship, directly contradicting the idea of generic AI writing.\n\n**Concrete signs against generic AI writing:**\n\n*   **Specific Naming & Context:** The post includes a high density of specific, unique details: \"DurJam,\" \"Godot Tutorial for DurHack 2024,\" \"Durham University Computing Society Game Jam..."}}},{name="Alex Aumais",linkedin="linkedin.com/in/alex-aumais/",posts=3,average=0.0029,classification="human",posts_data={{text="Announcing the secret project I've been working on the last year! We think Hacker Badges will rev...",probability=4.854188612477665e-05,class="human",report="As a writing-quality investigator, here's a review of the LinkedIn post:\n\n**Signs Consistent with Generic AI Writing:**\n\n*   **Buzzword Reliance:** The use of \"revolutionize\" is a common, high-impact buzzword frequently employed in AI-generated promotional content to convey significant change without specific detail.\n*   **Formulaic Benefit Listing:** The..."},{text="Part badge, part mini computer, the Hacker Badge is your interactive companion for exploring ever...",probability=0.008720264419077663,class="human",report="This LinkedIn post exhibits characteristics common in concise, promotional marketing copy, whether generated by AI or a human.\n\n**Signs of generic AI writing:** The language is polished, grammatically correct, and uses common marketing tropes like \"interactive companion,\" \"explore, experiment and dream bigger,\" and \"adds a new layer.\" While this contribut..."},{text="Had a blast speaking at Major League Hacking Hackcon last week! I love crazy ideas, so it was awe...",probability=7.809948756511512e-05,class="human",report="This LinkedIn post exhibits several human-like qualities that differentiate it from typical generic AI writing:\n\n*   **Informal & Conversational Tone:** Phrases like \"Had a blast,\" \"I love crazy ideas,\" \"awesome to share,\" and \"pulling off\" contribute to a natural, personal voice. Generic AI often defaults to more formal or neutral language.\n*   **Use of..."}}},{name="Alex Cui",linkedin="linkedin.com/in/alex-cui-caltech/",posts=3,average=0.1657,classification="human",posts_data={{text="Edward Tian built GPTZero, one of the most widely used AI detection tools. He shared his 4 princi...",probability=7.86289832662438e-06,class="human",report="This LinkedIn post contains a significant **unsupported factual claim** and potential **manipulation**.\n\nThe claim \"GPTZero was acquired by Superhuman in June\" appears to be false. As of September 2026, there is no public record or announcement of GPTZero being acquired by Superhuman, nor is Edward Tian listed as having left GPTZero or joined Superhuman...."},{text="It was bittersweet when I got this message from my team\n\n100s of mints, tote bags, bottle-openers...",probability=1.3687977589947439e-05,class="human",report="The post exhibits few signs of generic AI writing; its informal tone (\"AI slop,\" \"watch out\") and human-like phrasing suggest a native speaker or a highly refined AI.\n\nHowever, it contains significant unsupported factual claims and potential manipulation:\n\n1.  **Unsupported Claim/Manipulation:** The assertion \"we used to ensure all of IJCAI's accepted pap..."},{text="Superhuman users have been asking us for a notetaker for a long time. Meeting notes are one of th...",probability=0.4969609177258295,class="mixed",report="As a writing-quality investigator, here's an analysis of the LinkedIn post, keeping in mind that a detector score is not proof:\n\n**Signs of Generic AI Writing:**\n\n*   **Reliance on Common Business Jargon and Clichés:** Phrases like \"clearest, most valuable places where AI can help,\" \"excellent product,\" \"deep expertise,\" \"fits naturally,\" and \"set a new b..."}}},{name="Allison Salas Irus",linkedin="linkedin.com/in/allison-salas-irus/",posts=3,average=0.0031,classification="human",posts_data={{text="Today is my first day at GPTZero. Again.\n\nA little over a year ago, Top Funnel Talent was working...",probability=3.915752968910248e-05,class="human",report="This LinkedIn post shows no concrete signs of generic AI writing, unsupported factual claims, or manipulation.\n\n**Concise Explanation:**\nThe post is rich with personal anecdotes (e.g., \"Mom said better things were coming,\" \"COVID took my new grad dream job\"), specific names (Edward Tian, Alex Cui, Anthony Escamilla), and informal, expressive language (e.g..."},{text="This week, it became official: GPTZero joined Superhuman to build the #1 AI transparency platform...",probability=0.00012951431261412603,class="human",report="Despite the 0.0% AI generation probability, the post exhibits several characteristics common in generic, formulaic writing often produced by AI (and humans trained on similar content):\n\n*   **Aspirational Claim:** The assertion of building \"the #1 AI transparency platform\" is a subjective, aspirational goal presented as a definitive statement, rather than..."},{text="We just got some great new hires and are still looking for the best engineers in NYC and Toronto! 🌍",probability=0.00899040689318892,class="human",report="This post shows no concrete signs of generic AI writing. It is remarkably concise and uses natural, direct language (\"We just got some great new hires,\" \"still looking for the best engineers\"). There are no awkward phrases, overly formal or repetitive structures, or generic filler often associated with AI.\n\nRegarding claims: \"We just got some great new hi..."}}},{name="Julius Bort",linkedin="linkedin.com/in/juliusbort/",posts=3,average=0.5594,classification="ai",posts_data={{text="Really enjoyed supporting Per Scholas learners during their Amazon visit. Mock interviews like th...",probability=0.5680737174911158,class="ai",report="Based on the writing quality, here's an assessment:\n\nThe post exhibits signs of generic AI writing due to its highly conventional and clichéd phrasing. The statement \"Mock interviews like these are a great way to bridge the gap between classroom learning and real-world career preparation\" uses common buzzwords and a widely accepted, but unoriginal, observ..."},{text="With the summer fast approaching, I'm pleased to announce that I will be joining Amazon as an Ope...",probability=1,class="ai",report="This LinkedIn post displays several characteristics commonly associated with generic AI-generated content:\n\n*   **Chronological Inconsistency:** The phrase \"With the summer fast approaching\" is out of sync with the current date (September 2026). An internship \"this summer\" would refer to Summer 2026, which is now past. This suggests a lack of real-world t..."},{text="I’m proud to announce that I’ll be returning to Amazon this summer as a Sourcing Recruiter Intern...",probability=0.11023839831954568,class="human",report="This post exhibits **signs of generic AI writing** through its heavy reliance on common professional platitudes and a predictable structure. Phrases like \"dynamic team,\" \"fast-paced world,\" \"incredible mentors who challenged me, supported my growth,\" \"Amazon’s innovative culture,\" \"recruit top talent,\" and \"learn from the best\" are frequently used in corp..."}}}}

local mode = "list"
local selected = 1
local page = 0
local detail_scroll = 0
local detail_text = ""
local title
local body
local status
local hint
local contact_count = 0

local function percent(value)
	return math.floor(value * 100 + 0.5) .. "%"
end

local function set_leds(r, g, b)
	badge.led.set_all(r, g, b)
	badge.led.show()
end

local function csv_cell(value)
	local text = tostring(value or "")
	return '"' .. string.gsub(text, '"', '""') .. '"'
end

local function snapshot_contacts()
	contact_count = badge.contacts.count()
	local lines = {"name,role,badge_id,received_unix"}
	for index = 1, contact_count do
		local contact = badge.contacts.get(index)
		if contact then
			lines[#lines + 1] = table.concat({
				csv_cell(contact.name),
				csv_cell(contact.role),
				csv_cell(contact.badge_id),
				csv_cell(contact.received_unix)
			}, ",")
		end
	end
	badge.fs.write("appdata/contacts.csv", table.concat(lines, "\n"))
end

local function paint_list()
	mode = "list"
	page = 0
	detail_scroll = 0
	title:set_text("Linked-Zero  " .. selected .. "/" .. #profiles)
	local lines = {}
	for index = 1, #profiles do
		local mark = index == selected and "> " or "  "
		local profile = profiles[index]
		lines[#lines + 1] = mark .. profile.name .. "  " .. percent(profile.average)
	end
	body:set_text(table.concat(lines, "\n"))
	status:set_text("A open / " .. contact_count .. " contacts snapshotted")
	hint:set_text("UP/DOWN select   A open\nHOME exit")
	set_leds(0, 48, 96)
end

local function paint_detail()
	local profile = profiles[selected]
	mode = "detail"
	if page < 1 then
		title:set_text(profile.name .. "  " .. percent(profile.average))
		detail_text = profile.linkedin .. "\n\nGPTZero: " .. profile.classification ..
			"\nPosts analyzed: " .. profile.posts ..
			"\nAverage AI probability: " .. percent(profile.average)
		status:set_text("Profile report")
		set_leds(255, 150, 0)
	else
		local post = profile.posts_data[page]
		title:set_text(profile.name .. "  POST " .. page .. "/3")
		detail_text = "GPTZero: " .. percent(post.probability) .. " " .. post.class ..
			"\n\n" .. post.text .. "\n\nBackboard:\n" .. post.report
		status:set_text("Full post report")
		if post.probability >= 0.7 then
			set_leds(180, 24, 24)
		elseif post.probability >= 0.45 then
			set_leds(255, 150, 0)
		else
			set_leds(24, 180, 90)
		end
	end
	if detail_scroll > #detail_text then
		detail_scroll = math.max(0, #detail_text - 190)
	end
	body:set_text(string.sub(detail_text, detail_scroll + 1, detail_scroll + 190))
	status:set_text(detail_scroll > 0 and "Scrolled report" or
		(page < 1 and "Profile report" or "Full post report"))
	hint:set_text("UP/DOWN scroll   A next page\nL/R post   B back")
end

function on_enter(root)
	snapshot_contacts()
	local background = badge.ui.box(root, 312, 232)
	background:set_pos(4, 4)
	background:style({bg_color = 0x101820, radius = 6})
	title = badge.ui.label(background, "Linked-Zero")
	title:style({text_font = 20, text_color = 0xffffff})
	title:set_pos(12, 10)
	body = badge.ui.label(background, "")
	body:style({text_font = 16, text_color = 0xd7e6f2})
	body:set_pos(12, 42)
	body:set_size(288, 118)
	status = badge.ui.label(background, "")
	status:style({text_font = 14, text_color = 0xffc857})
	status:set_pos(12, 166)
	hint = badge.ui.label(background, "")
	hint:style({text_font = 14, text_color = 0xaec4d4})
	hint:set_pos(12, 190)
	paint_list()
end

function on_button(button, kind)
	if kind ~= badge.input.KIND.PRESSED then return end
	local B = badge.input.BUTTON
	if mode == "list" then
		if button == B.UP then
			selected = (selected - 2) % #profiles + 1
			paint_list()
		elseif button == B.DOWN then
			selected = selected % #profiles + 1
			paint_list()
		elseif button == B.A then
			paint_detail()
		end
	else
		if button == B.B then
			paint_list()
		elseif button == B.UP then
			detail_scroll = math.max(0, detail_scroll - 150)
			paint_detail()
		elseif button == B.DOWN then
			detail_scroll = detail_scroll + 150
			paint_detail()
		elseif button == B.A then
			detail_scroll = 0
			page = (page + 1) % 4
			paint_detail()
		elseif button == B.LEFT then
			detail_scroll = 0
			page = page == 0 and 3 or (page - 2) % 3 + 1
			paint_detail()
		elseif button == B.RIGHT then
			detail_scroll = 0
			page = page == 0 and 1 or page % 3 + 1
			paint_detail()
		end
	end
end

function on_exit()
	badge.led.clear()
	badge.led.show()
end
